# Change these first
owner: aperta-principium # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://interclip.app
  - name: Set API
    url: https://interclip.app/includes/api?url=https://www.linguee.com/english-german/translation/meanbusiness.html
  - name: Get API
    url: https://interclip.app/includes/get-api?code=tasks

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.interclip.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/aperta-principium/Interclip/main/img/interclip_logo.png
  name: Interclip status
  introTitle: "Want to check the uptime of **Interclip** and it's components? This is the place to do so."
  introMessage: Below are the charts as well as the current status of Interclip's server components such as: our image proxy, our API, mobile app and downloads.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
